name: xWarp
version: 2.6.5 b4
main: me.taylorkelly.mywarp.MyWarp
description: Implementation to create warp points!
authors:
  - 'xZise'
  - 'tkelly'
commands:
  warp:
    description: Warp commands
    usage: /<command> help - Displays the help for xWarp
    aliases: [xwarp]
