name: xWarp
version: 2.6.3
main: me.taylorkelly.mywarp.MyWarp
authors:
  - 'xZise'
  - 'tkelly'
commands:
  xwarp:
    description: Warp commands
    usage: /<command> help - Displays the help for xWarp
    parser: Quoted
